### ISSUE TITLE
HTTPS解密, 请求错误

### ISSUE THREAD

**Issue by amersons** [ouqiang/mars#1]
- HTTPS解密, 请求错误: x509: cannot validate certificate for 183.232.25.151 because it doesn't contain any IP SANs 配置https一直是这个问题，证书也安装了

**Comment by ouqiang** [comment]
直接通过浏览器访问，看下是不是这个ip证书无效发自我的iPhone------------------ 原始邮件 ------------------发件人: notifications@github.com <notifications@github.com>发送时间: 2019年9月27日 19:09收件人: ouqiang/mars <mars@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[ouqiang/mars] HTTPS解密, 请求错误 (#1)
HTTPS解密, 请求错误: x509: cannot validate certificate for 183.232.25.151 because it doesn't contain any IP SANs 配置https一直是这个问题，证书也安装了


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ouqiang/mars/issues/1?email_source=notifications\u0026email_token=AC4ZP37RVAYDWWL7KKFPX43QLXSVPA5CNFSM4I3FBES2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOD73EQ",
"url": "https://github.com/ouqiang/mars/issues/1?email_source=notifications\u0026email_token=AC4ZP37RVAYDWWL7KKFPX43QLXSVPA5CNFSM4I3FBES2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOD73EQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ghost** [comment]
https 抓包失败了 ssl开关也打开了 错误代码：SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by ouqiang** [comment]
所有HTTPS站点都失败，还是某一个？

**Comment by ghost** [comment]
所有的，我是通过 iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
转发的流量。大佬可以复现一下。

**Comment by ouqiang** [comment]
不配置iptables呢，不做任何修改。

**Comment by ghost** [comment]
可以抓到，包但是http又不好使了。为什么我使用iptables 过来的https 流量却不行、

**Comment by ouqiang** [comment]
http又不好使了是什么意思，不能代理http请求

**Comment by ouqiang** [comment]
通过iptables直接在服务端转发流量，客户端无感知是吗

**Comment by ghost** [comment]
对的无感知，强制客户安装ca证书。iptables可以获取http流量，https就提示SSL_ERROR_RX_RECORD_TOO_LONG。我觉得应该是代码有点问题。

**Comment by ouqiang** [comment]
客户端设置代理访问https正常ok的，没试过通过iptables来转发流量

**Comment by ghost** [comment]
您能给看看嘛 有偿提供修改bug。

**Comment by ouqiang** [comment]
什么情况下会用到iptables转发流量

**Comment by ghost** [comment]
做流量分析的时候，会用到，普通情况也不会用go写的代理呀。

**Comment by ghost** [comment]
如何改为透明代理？

**Comment by ouqiang** [comment]
从tls握手协议中解析出 host
