### ISSUE TITLE
中间人iptables如何配置

### ISSUE THREAD

**Issue by mel2oo** [ouqiang/mars#6]
在服务器端运行程序，kvm虚拟机内流量通过iptables重定向到服务端代理端口，但好像流量过来后没有成功转发

**Comment by ouqiang** [comment]
不支持https发自我的iPhone------------------ 原始邮件 ------------------发件人: ***@***.*** ***@***.***>发送时间: 2021年8月8日 10:36收件人: ouqiang/mars ***@***.***>抄送: Subscribed ***@***.***>主题: 回复：[ouqiang/mars] 中间人iptables如何配置 (#6)
在服务器端运行程序，kvm虚拟机内流量通过iptables重定向到服务端代理端口，但好像流量过来后没有成功转发

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ouqiang/mars/issues/6",
"url": "https://github.com/ouqiang/mars/issues/6",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
